### PR TITLE
use version > 2.8.3 for psycopg from python version 3.8

### PR DESCRIPTION
**Pull request by signedav**
https://github.com/psycopg/psycopg2/issues/854#issuecomment-611791946

### CODE REVIEW

**Comment by signedav** [comment]
Or could we just remove the version, then it installs the latest? 

Why we defined the version on psycopg at all?

**Comment by m-kuhn** [comment]
Clicking through git blame: https://github.com/opengisch/QgisModelBaker/pull/180#pullrequestreview-113083161

So `psycopg2>=2.7.4` should be the way to go

**Comment by signedav** [comment]
> Clicking through git blame: [#180 (review)](https://github.com/opengisch/QgisModelBaker/pull/180#pullrequestreview-113083161)
> 
> So `psycopg2>=2.7.4` should be the way to go

But we need >=2.8.3 with python 3.8 ... can we do that or might there be a problem, with environments having python versions < 3.8?

**Comment by signedav** [comment]
Or does it install with your suggestion the latest version anyway when using python 3.8?

**Comment by m-kuhn** [comment]
> Or does it install with your suggestion the latest version anyway when using python 3.8?

if it doesn't let's stick to your solution but with a `>=` in the psycopg version as well

**Comment by signedav** [comment]
I can do a test run.

**Comment by signedav** [comment]
And it works :taco: Thanks @m-kuhn I approve your suggestion :-)

**Pull request merged**
