### PR TITLE
Mssql support with docker testing

### PR DESCRIPTION
**Pull request by 3nids**
work in progress

### CODE REVIEW

**Comment by 3nids** [comment]
@gacarrillor this is now working, you can cherry-pick my commit 1b29677 in the other PR

**Comment by m-kuhn** [comment]
@3nids @gacarrillor thanks for moving this ahead!

I'd like to merge this soon. Which one is the proper PR to review, this or #288?

**Comment by m-kuhn** [comment]
@3nids should the mssql_support_docker branch be deleted too?

**Comment by 3nids** [comment]
Just wait for the other to be merged so we still have the commit available.

**Comment by m-kuhn** [comment]
:+1:

**Pull request closed without merging**
