### PR TITLE
Integration of Linking Relation Editor

### PR DESCRIPTION
**Pull request by domi4484**

### CODE REVIEW

**Review by signedav — APPROVED** [review]

**Comment by signedav** [comment]
Still let them test first...

**Comment by signedav** [comment]
And maybe it would make sense model baker uses it already?

**Comment by domi4484** [comment]
> And maybe it would make sense model baker uses it already?

Yes, I am just having some troubles to replace the widget type with the new one. I am doing this [here](https://github.com/opengisch/QgisModelBaker/blob/8c007cb1c3fbb525399deeb76afe0e6c66759182/QgisModelBaker/libqgsprojectgen/dataobjects/form.py#L119) with `widget.setRelationWidgetTypeId("linking_relation_editor")` but when generating the project the information get lost.
I have do dig into it

**Comment by signedav** [comment]
Is it possible to make the plugin dependency depending on the QGIS version? Since I suppose linking relation editor does not work for 3.16 (and maybe nor for 3.22)?

**Comment by domi4484** [comment]
> Is it possible to make the plugin dependency depending on the QGIS version?

From what I have seen it is not possible


> Since I suppose linking relation editor does not work for 3.16 (and maybe nor for 3.22)?

It works from version 3.18.

**Comment by domi4484** [comment]
@signedav Installing ModelBaker on QGIS 3.16 would show the following window, but the plugin can still be installed:
image

**Comment by signedav** [comment]
If you press "cancel"? Well, fair enough.

**Comment by signedav** [comment]
Can you confirm that when the project is created with >3.16 and the Linking Relation Editor is chosen as widget, I get a proper Relation Editor Widget when I open it on 3.16 (with or without having Model Baker installed)?

**Comment by domi4484** [comment]
> If you press "cancel"? Well, fair enough.

It makes no difference, the plugin get also installed successfully 🤔 Should this be considered a qgis bug?




> Can you confirm that when the project is created with >3.16 and the Linking Relation Editor is chosen as widget, I get a proper Relation Editor Widget when I open it on 3.16 (with or without having Model Baker installed)?

I can't tell you at the moment because I don't even get it to use the new widget for >3.16. Still have to find out why, this is how I was trying:


> Yes, I am just having some troubles to replace the widget type with the new one. I am doing this [here](https://github.com/opengisch/QgisModelBaker/blob/8c007cb1c3fbb525399deeb76afe0e6c66759182/QgisModelBaker/libqgsprojectgen/dataobjects/form.py#L119) with `widget.setRelationWidgetTypeId("linking_relation_editor")` but when generating the project the information get lost.
> I have do dig into it

**Comment by signedav** [comment]
> Should this be considered a qgis bug?

Hm... little confusing that okay and cancel does the same. Maybe a "minor" bug. But what should be the behavior? Cancel cancels the installation? Or cancel cancels the dependency?

> I can't tell you at the moment because I don't even get it to use the new widget for >3.16. Still have to find out why, this is how I was trying

Okay, just check it before we publish.

**Comment by signedav** [comment]
After your fix, do you know about that @domi4484 ?
> Can you confirm that when the project is created with >3.16 and the Linking Relation Editor is chosen as widget, I get a proper Relation Editor Widget when I open it on 3.16 (with or without having Model Baker installed)?

**Comment by domi4484** [comment]
> After your fix, do you know about that @domi4484 ?
> 
> > Can you confirm that when the project is created with >3.16 and the Linking Relation Editor is chosen as widget, I get a proper Relation Editor Widget when I open it on 3.16 (with or without having Model Baker installed)?

@signedav yes I can confirm it.

**Comment by signedav** [comment]
Is it still wip?

**Comment by domi4484** [comment]
No sorry, i removed the draft label

**Comment by signedav** [comment]
To merge after succesful tests (besides autoflake)

**Comment by signedav** [comment]
Good to merge?

**Comment by signedav** [comment]
Welcome Linking Relation Editor :wave:

Thanks @domi4484

**Pull request merged**
