### PR TITLE
Show warning message in TID manager when OIDs cannot be found

### LINKED ISSUE #925: OID manager does not open when there are no layers in QGIS LayerTree
Python exception is thrown:

```
AttributeError: 'NoneType' object has no attribute 'tool' 
Traceback (most recent call last):
  File "/home/germap/.local/share/QGIS/QGIS3/profiles/test_plugins/python/plugins/QgisModelBaker/qgismodelbaker.py", line 363, in show_tidmanager_dialog
    self.tidmanager_dlg = TIDManagerDialog(
  File "/home/germap/.local/share/QGIS/QGIS3/profiles/test_plugins/python/plugins/QgisModelBaker/gui/tid_manager.py", line 49, in __init__
    self.tid_configurator_panel.setup_dialog(QgsProject.instance())
  File "/home/germap/.local/share/QGIS/QGIS3/profiles/test_plugins/python/plugins/QgisModelBaker/gui/panel/tid_configurator_panel.py", line 71, in setup_dialog
    self._reset_tid_configuration()
  File "/home/germap/.local/share/QGIS/QGIS3/profiles/test_plugins/python/plugins/QgisModelBaker/gui/panel/tid_configurator_panel.py", line 75, in _reset_tid_configuration
    self.set_sequence_panel.set_configuration(self.configuration)
  File "/home/germap/.local/share/QGIS/QGIS3/profiles/test_plugins/python/plugins/QgisModelBaker/gui/panel/set_sequence_panel.py", line 41, in set_configuration
    self.pg_use_super_login.setVisible(self.configuration.tool & DbIliMode.pg)
AttributeError: 'NoneType' object has no attribute 'tool'

```

Model Baker v7.8.4
QGIS 3.28.x and QGIS master (3.37)

### PR DESCRIPTION
**Pull request by gacarrillor**
Fix #925 

image

### CODE REVIEW

**Comment by signedav** [comment]
Code looks good but I wonder if a message box would be nicer. This Warning Bar for me looks like an error and not like an information that it does not make sense to use this dialog. Maybe just grayed out everything makes sense as well.

**Comment by gacarrillor** [comment]
> Code looks good but I wonder if a message box would be nicer. This Warning Bar for me looks like an error and not like an information that it does not make sense to use this dialog. Maybe just grayed out everything makes sense as well.

I'll try with a message box to let the user know why the dialog is grayed out.

**Comment by gacarrillor** [comment]
@signedav,  BTW, yesterday I think I finally did it with a message bar because I saw we had this message for a similar case in the Dataset Manager (i.e., empty project, probably first time opening Model Baker dialogs):

image

Should we bring a message box also for this Dataset Manager or we leave it as is and implement a message box for the OID Manager anyways?

**Comment by signedav** [comment]
```
To use the OID Manager, configure a connection to an INTERLIS based database.
```

**Review by signedav — APPROVED** [review]

**Pull request merged**
