### PR TITLE
resolves ili2db4 tests

### PR DESCRIPTION
**Pull request by lacardonap**
- [x] Upgrade dump: change column name owner by colowner in t_ili2db_attrname. Note: I could not generate the database with the model GL_Nutzungsplanung_V1 because the model is not available, now the models for versions 1_3, 1_4 are available.
- [x] The faults associated with the tests are resolved

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thank you for looking at this @lacardonap 

We will probably need a different approach for that. These tests are currently failing for a good reason: if someone has a ili2db3 created database in production, he will see errors instead of experiencing a smooth upgrade path. So these dumps must remain unchanged and model baker must be able to handle them gracefully.

@signedav will look at this later this month, if you also planned to work more on this, please coordinate the steps with him.

**Comment by gacarrillor** [comment]
> We will probably need a different approach for that. These tests are currently failing for a good reason: if someone has a ili2db3 created database in production, he will see errors instead of experiencing a smooth upgrade path. **So these dumps must remain unchanged and model baker must be able to handle them gracefully.**

Then I think it makes sense the dumps and Geopackage databases are in both modes: ili2db3 and ili2db4. ili2db4's ones are already passing with this PR :+1: , now what's left is to work on the ili2db3's ones.


> @signedav will look at this later this month, if you also planned to work more on this, please coordinate the steps with him.

Nice! Remember that we already say something about what Model Baker could do for an existing ili2db3 schema (see https://github.com/opengisch/QgisModelBaker/pull/317#issuecomment-518679699).

**Comment by m-kuhn** [comment]
> Then I think it makes sense the dumps and Geopackage databases are in both modes: ili2db3 and ili2db4. ili2db4's ones are already passing with this PR +1 , now what's left is to work on the ili2db3's ones.

Good idea :+1: 

Can you add exactly what's done in here as new tests?

**Comment by lacardonap** [comment]
These are the adjusted tests.

## TEST: test_kbs_postgis

```python3
======================================================================
FAIL: test_kbs_postgis (test_projectgen.TestProjectGen)
======================================================================
Traceback (most recent call last):
  File "/usr/src/QgisModelBaker/tests/test_projectgen.py", line 101, in test_kbs_postgis
    'bemerkung_de']))
AssertionError: Items in the first set but not the second:
'bemerkung_lang'
Items in the second set but not the first:
'bemerkung_de'
'bemerkung_fr'
'bemerkung_en'
'bemerkung_it'
'bemerkung_rm'
```

Solution: Additional items are removed and missing items are added.

## TEST: test_export_postgis

```python3
======================================================================
FAIL: test_export_postgis (test_export.TestExport)
======================================================================
Traceback (most recent call last):
  File "/usr/src/QgisModelBaker/tests/test_export.py", line 131, in test_export_postgis
    self.assertEqual(exporter.run(), iliexporter.Exporter.SUCCESS)
AssertionError: 1000 != 0
```

Solution: Add all the models to use in the parameter ilimodels.

## TEST: test_export_geopackage

```python3
======================================================================
FAIL: test_export_geopackage (test_export.TestExport)
======================================================================
Traceback (most recent call last):
  File "/usr/src/QgisModelBaker/tests/test_export.py", line 57, in test_export_geopackage
    self.assertEqual(exporter.run(), iliexporter.Exporter.SUCCESS)
AssertionError: 1000 != 0
```

Solution: Add all the models to use in the parameter ilimodels.

Inputs are updated using ili2db4:
* test_ciaf_ladm.xtf
* test_export.gpkg

## TEST: test_ili2pg_dump_without_metattr

* There is no colowner column in table t_ili2db_attrname.
* When restoring the database dump all layers cannot be restored because there is no uuid_generate_v4 function.

Solution:
* The dump file is updated: The owner column is renamed by colowner in the t_ili2db_attrname table.
* The uuid-ossp extension is installed if it does not exist.

**Comment by m-kuhn** [comment]
@lacardonap I meant, can you create a new commit here (or a new pull request) that duplicates the tests with new versions instead of replacing the current tests? Thanks a lot!

**Comment by lacardonap** [comment]
@m-kuhn Yeah, okay. I will create a new PR with the indicated changes.

**Pull request closed without merging**
