### PR TITLE
Changes to ili2db4 branch

### PR DESCRIPTION
**Pull request by gacarrillor**
:warning:  PR for merging to ili2db4 branch :warning: 

Changes in this PR:

 + Update ili2db4 to 4.2.0 (https://github.com/opengisch/QgisModelBaker/pull/343/commits/2fafe71a736b4432f43964a55e2a5a6557c2025f)
 + Remove custom parser for relations Domain-Class since https://github.com/claeis/ili2db/issues/19 was solved in ili2db4. (https://github.com/opengisch/QgisModelBaker/pull/343/commits/07604ba36420d7a8c8e47b65c3a1194c8fd997a3)

 + Cherry-picks to bring PRs already merged in master (each PR merged in master is a single commit in current PR): 
    + Adjust Java version parsing #320 (https://github.com/opengisch/QgisModelBaker/pull/343/commits/80e9446e100be8325be49247107cc9bbb95f5860)
    + Avoid critical message that always appears when installing Model Baker #328 (https://github.com/opengisch/QgisModelBaker/pull/343/commits/f694b18aedb712f01a9e91d22e5c95adfc9b3c1c)
    + Check that ili file exists before refreshing cache #329 (https://github.com/opengisch/QgisModelBaker/pull/343/commits/a4c19018706f337eb3ca8c84f8b7182d2163817b)
    + Not trying to get models when the scheme is not interlis #330 (https://github.com/opengisch/QgisModelBaker/pull/343/commits/1e813111e773e53a63392b49d9cdb004e2f68dec)
    + Load Panel Settings from UI file #331 (https://github.com/opengisch/QgisModelBaker/pull/343/commits/85419431f21a69e58e7ed9089e43b3ad1f588bad)
    + Add "import/export without validating" button #332 (https://github.com/opengisch/QgisModelBaker/pull/343/commits/e97e7729dbc15280c53dd85bc8ead9339265c187)
        + 4 commits: 3 squashed, 1 applied manually (#334) (https://github.com/opengisch/QgisModelBaker/pull/343/commits/80780ba57583cad8a34381a705bec909b72d9dc4).
    + Refresh panels when switching modes in Generate Project dialog #336 (https://github.com/opengisch/QgisModelBaker/pull/343/commits/9a9988142e4e3ba03818c9e43474c4b892c094ce)
    + Follow up for fixing issue 325 #339 (https://github.com/opengisch/QgisModelBaker/pull/343/commits/81cd9d733823fb00faa18019e159ee570639bac2)

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks!
Would it be possible to split the changes into different pull requests?
I understand that now with those ili2db4 changes this might be hard, so if it is, please say so. Otherwise, it would make the review process a lot easier.

**Comment by gacarrillor** [comment]
I'm doing my best to bring each PR already merged in master into a single commit in this PR (section cherry-picks in the PR description). In this way you can easily compare the commit with the changes each singe PR introduced to master. 

If you don't mind I'd like to do all of this "maintenance" in this PR. I'll improve the description to map each single commit there to ease the review phase and I'll also consider your suggestion for new changes/features.

**Comment by m-kuhn** [comment]
If it makes it easier for this branch, please proceed as is :+1: 

If there's any chance to split off individual chunks (here or wherever) the smaller the PR, the likelier a quick merge :)

**Comment by gacarrillor** [comment]
Makes sense. If you need any help when reviewing/merging these changes, please let me know, we could make it together.

**Pull request merged**
