### PR TITLE
Update schemas in separate task to avoid freezes

### LINKED ISSUE #848: Problem on updating schema config
1. when I change something in the form (e.g. database) it does not update the schema dropdown
[Screencast from 24.11.2023 11:30:49.webm](https://github.com/opengisch/QgisModelBaker/assets/28384354/fafee81a-71f4-4975-ba19-417a9d949cc0)

2. when I don't have the correct credentials but everything else is correct, the GUI freezes (maybe because of long responsetime of the remote server)
image

### PR DESCRIPTION
**Pull request by domi4484**
Fix #848

### CODE REVIEW

**Comment by domi4484** [comment]
The same super long freeze is present in older MB versions when entering db.sob.opengis.ch, wrong port, and pressing the `Next` button. In each case when executed in a thread it should not block... I'll try to find out where it locks

**Comment by signedav** [comment]
> The same super long freeze is present in older MB versions when entering db.sob.opengis.ch, wrong port, and pressing the Next button. In each case when executed in a thread it should not block... I'll try to find out where it locks

Hm... Or when it takes that long maybe a shorter time out would be cool. Or don't we have it in our hands and it's a server thing?

**Comment by signedav** [comment]
Why it checks ili2db version? 🤔

**Comment by domi4484** [comment]
Its not necessary, I copy pasted too much code 😅

**Review by signedav — APPROVED** [review]
Cool. That looks good.

**Pull request merged**
