### PR TITLE
Concern superuser login on receiving schema

### PR DESCRIPTION
**Pull request by signedav**

### CODE REVIEW

**Comment by signedav** [comment]
- [ ] Database or schema does not exist <-- can b e optimized

**Review by gacarrillor — APPROVED** [review]
Good! I stumbled upon this issue recently.

**Comment by gacarrillor** [comment]
> * [ ]  Database or schema does not exist <-- can b e optimized

Is it related to this issue?
https://github.com/opengisch/QgisModelBaker/issues/967

**Comment by signedav** [comment]
> Is it related to this issue?
> https://github.com/opengisch/QgisModelBaker/issues/967

Stumbled over this when I tried to fix 967 - there I cannot reproduce it, but maybe they are connected. Asked the user to test it..

**Comment by gacarrillor** [comment]
> > Is it related to this issue?
> > #967
> 
> Stumbled over this when I tried to fix 967 - there I cannot reproduce it, but maybe they are connected. Asked the user to test it..

I remember I saw that message (`Database or schema does not exist`) once, and had no clue about what happened. Don't remember anymore the situation or how to reproduce, though.

**Pull request merged**
