### PR TITLE
[gui] load panel settings from ui file

### PR DESCRIPTION
**Pull request by lacardonap**
This PR moves the GUI part from Python code to UI files for easing maintenance.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks, does this change the UI?
Can you add a screenshot in this case?

**Comment by lacardonap** [comment]
The UI does not change.

**PostgreSQL settings panel**
pg_settings_panel

**Example: Import data with PostgreSQL**

import_interlist_data_pg


**GeoPackage settings panel**
gpkg_settings_panel

**Example: Import data with GeoPackage**

import_interlist_data_gpkg

**Comment by m-kuhn** [comment]
> The UI does not change.

Then, what does it change?

**Comment by gacarrillor** [comment]
@m-kuhn, this PR moves the GUI part from Python code to UI files for easing maintenance.

**Pull request merged**
