### PR TITLE
ili2db also works with newer java version

### PR DESCRIPTION
**Pull request by m-kuhn**
No longer force people to use legacy versions of java

### CODE REVIEW

**Comment by m-kuhn** [comment]
@gacarrillor what do you think?
Works here with 

```
java --version
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment 18.9 (build 11.0.9+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9+11, mixed mode, sharing)
```

**Comment by signedav** [comment]
Is this okay? Can we put that into 6.3.2 release?

**Comment by m-kuhn** [comment]
I think so, yes.
It should not break any existing installation (java 8 still works), it is tested here with java 11. Worst that can happen (unlikely IMHO) is that it does not work on some newer java version somewhere and either ili2db receives a fix or we revert this patch.

**Review by signedav — APPROVED** [review]
LGTM

**Comment by signedav** [comment]
Mässi :-)

**Pull request merged**
